import { TempDataService } from '../temp/temp_file_dataService.js?v=20260901-1';
import { TempSessionService } from '../temp/temp_file_sessionService.js?v=20260901-1';

const session = TempSessionService.requireRole('admin','manager');
if (!session) throw new Error('Admin or Manager login required.');
const dataService = new TempDataService();
const $ = id => document.getElementById(id);
function message(id, text, success=false) { $(id).textContent=text; $(id).className=`message ${success?'success':'error'}`; }
function uniqueId(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; }

$('newUsername').addEventListener('input', () => { $('newPassword').value = $('newUsername').value.trim() ? `${$('newUsername').value.trim()}@123` : ''; });
if (session.role === 'manager') {
  $('newRole').value = 'employee';
  $('newRole').disabled = true;
}

$('medicalForm').addEventListener('submit', async event => { event.preventDefault(); const name=$('medicalName').value.trim(); const area=$('medicalArea').value.trim(); if(!name) return message('medicalMessage','Medical name is required.'); try { const existing=await dataService.getMedicals(); if(existing.some(item=>String(item.name).trim().toLowerCase()===name.toLowerCase() && String(item.area||'').trim().toLowerCase()===area.toLowerCase())) throw new Error('Medical already exists.'); await dataService.addMedical({id:uniqueId('MED'),name,area,is_active:true,admin_id:session.admin_id||1}); event.target.reset(); message('medicalMessage','Medical added successfully.',true); } catch(error) { message('medicalMessage',error.message); } });

$('userForm').addEventListener('submit', async event => { event.preventDefault(); const username=$('newUsername').value.trim(); const role=$('newRole').value; if(!username) return message('userMessage','Username is required.'); if(session.role==='manager' && role!=='employee') return message('userMessage','Managers can create employees only.'); try { const existing=await dataService.getUsers(); if(existing.some(item=>item.username.toLowerCase()===username.toLowerCase())) throw new Error('Username already exists.'); await dataService.addUser({id:uniqueId('USR'),username,password_hash:await dataService.sha256(`${username}@123`),role,is_active:true,admin_id:session.admin_id||1,created_at:new Date().toISOString()}); event.target.reset(); $('newPassword').value=''; message('userMessage',`User created. Initial password: ${username}@123`,true); } catch(error) { message('userMessage',error.message); } });

function readProductForm() { const name=$('productName').value.trim(); return { id:$('productId').value.trim() || uniqueId('PROD'), code:$('productCode').value.trim(), name, unit:$('productUnit').value.trim(), mrp:Number($('productMrp').value||0), formula:$('productFormula').value.trim(), company:$('productCompany').value.trim(), is_active:true, admin_id:session.admin_id||1 }; }
$('productForm').addEventListener('submit', async event => { event.preventDefault(); const product=readProductForm(); if(!product.name) return message('productMessage','Product name is required.'); try { const existing=await dataService.getProducts(); if(existing.some(item=>String(item.id||'').toLowerCase()===String(product.id).toLowerCase())) throw new Error('Product ID already exists.'); await dataService.addProduct(product); event.target.reset(); message('productMessage','Product added successfully.',true); } catch(error) { message('productMessage',error.message); } });

let bulkProducts=[];
$('productJsonFile').addEventListener('change', async event => { bulkProducts=[]; const file=event.target.files?.[0]; if(!file) { $('jsonPreview').textContent='No JSON file selected.'; return; } try { const parsed=JSON.parse(await file.text()); bulkProducts=Array.isArray(parsed) ? parsed : (Array.isArray(parsed.products) ? parsed.products : []); if(!bulkProducts.length) throw new Error('JSON must contain a product array.'); if(bulkProducts.some(item=>!item || typeof item!=='object' || !String(item.name||'').trim())) throw new Error('Every product must have a name.'); $('jsonPreview').textContent=`${bulkProducts.length} product record(s) ready from ${file.name}.`; message('bulkProductMessage','JSON loaded. Review the count, then add.',true); } catch(error) { bulkProducts=[]; $('jsonPreview').textContent='Invalid JSON file.'; message('bulkProductMessage',error.message); } });
$('bulkProductButton').addEventListener('click', async () => { if(!bulkProducts.length) return message('bulkProductMessage','Please select a valid product JSON file first.'); try { const existing=await dataService.getProducts(); const ids=new Set(existing.map(item=>String(item.id||'').toLowerCase())); const products=[]; for(const raw of bulkProducts) { const product={...raw}; product.name=String(product.name||'').trim(); product.code=String(product.code||'').trim(); product.unit=String(product.unit||'').trim(); product.formula=String(product.formula||'').trim(); product.company=String(product.company||'').trim(); product.mrp=Number(product.mrp||0); product.id=String(product.id||'').trim() || uniqueId('BULK'); product.admin_id=session.admin_id||1; if(ids.has(product.id.toLowerCase())) throw new Error(`Duplicate Product ID: ${product.id}`); ids.add(product.id.toLowerCase()); product.is_active=product.is_active!==false; products.push(product); } for(const product of products) await dataService.addProduct(product); $('productJsonFile').value=''; bulkProducts=[]; $('jsonPreview').textContent='Import completed.'; message('bulkProductMessage',`${products.length} products added successfully.`,true); } catch(error) { message('bulkProductMessage',error.message); } });

TempSessionService.startExpiryWatcher(()=>location.replace('login.html'));
