import { TempSessionService } from '../temp/temp_file_sessionService.js';
import { TempDataService } from '../temp/temp_file_dataService.js';
const session=TempSessionService.requireRole('admin','manager','employee'); if(!session)throw new Error('Login required.');
const service=new TempDataService(),$=id=>document.getElementById(id);
$('logoutButton').onclick=()=>{TempSessionService.clear();location.replace('login.html')};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(row){return row?.is_pick===1||row?.is_pick===true?'Picked':row?.is_not_pick===1||row?.is_not_pick===true?'Not Picked':row?.is_call?'Pending':'Not Called'}
async function render(){const list=$('callingList'),filter=$('callingFilter')?.value||'all';try{const rows=await service.getCallingToday();const filtered=rows.filter(r=>{const s=status(r);return filter==='called'?r.is_call:filter==='not-called'?!r.is_call:filter==='pending'?s==='Pending':filter==='picked'?s==='Picked':filter==='not-picked'?s==='Not Picked':true});$('callingCount').textContent=`${filtered.length} of ${rows.length}`;list.innerHTML=filtered.length?filtered.map(r=>{const called=Boolean(r.is_call);const s=status(r);return `<article class="card callingRow"><div><strong>${esc(r.name)}</strong><div>${esc(r.area||'')}</div><div class="callingStatus">Status: ${called?'Called':'Not Called'} · ${s}</div></div><a class="btn primary callLink" data-id="${r.id}" data-phone="${esc(r.phone||'')}" href="${r.phone?`tel:${String(r.phone).replace(/[^0-9+]/g,'')}`:'#'}">${esc(r.phone||'No mobile number')}</a><div class="pickControls" data-medical="${r.id}" style="display:${called?'flex':'none'}"><label><input type="radio" name="pick-${r.id}" value="pick" ${s==='Picked'?'checked':''}> Picked</label><label><input type="radio" name="pick-${r.id}" value="not-pick" ${s==='Not Picked'?'checked':''}> Not Picked</label></div></article>`}).join(''):'<p>No medicals match this filter.</p>';
list.querySelectorAll('.callLink').forEach(a=>a.addEventListener('click',async e=>{const phone=a.dataset.phone;if(!phone){e.preventDefault();return}e.preventDefault();try{await service.recordCall(Number(a.dataset.id));window.location.href=`tel:${phone.replace(/[^0-9+]/g,'')}`;setTimeout(render,500)}catch(err){alert(err.message)}}));
list.querySelectorAll('.pickControls input').forEach(input=>input.addEventListener('change',async e=>{const id=e.target.closest('.pickControls').dataset.medical;try{await service.updateCallStatus(Number(id),e.target.value==='pick');await render()}catch(err){alert(err.message)}}))
}catch(e){list.innerHTML='<p>Calling list could not be loaded.</p>';}}
$('callingFilter')?.addEventListener('change',render);render();TempSessionService.startExpiryWatcher(()=>location.replace('login.html'));
