const SESSION_DURATION_MS = 12 * 60 * 60 * 1000;
const SESSION_VERSION = '4';
const SESSION_KEYS = ['hindPharmaUser','hindPharmaRole','hindPharmaToken','hindPharmaLoginTime','hindPharmaLoginAt','hindPharmaSessionVersion','hindPharmaAdminId','hindPharmaBusinessName','hindPharmaSubscriptionExpiry'];
const VALID_ROLES = ['super_admin','admin','manager','employee'];
export const TempSessionService={
save(user){const loginTime=Date.now();localStorage.setItem('hindPharmaUser',user.username);localStorage.setItem('hindPharmaRole',user.role||'employee');localStorage.setItem('hindPharmaToken',user.token);localStorage.setItem('hindPharmaLoginTime',String(loginTime));localStorage.setItem('hindPharmaSessionVersion',SESSION_VERSION);if(user.admin_id!=null)localStorage.setItem('hindPharmaAdminId',String(user.admin_id));else localStorage.removeItem('hindPharmaAdminId');if(user.business_name)localStorage.setItem('hindPharmaBusinessName',user.business_name);else localStorage.removeItem('hindPharmaBusinessName');if(user.subscription_expiry)localStorage.setItem('hindPharmaSubscriptionExpiry',user.subscription_expiry);else localStorage.removeItem('hindPharmaSubscriptionExpiry');sessionStorage.clear()},
get(){const token=localStorage.getItem('hindPharmaToken'),username=localStorage.getItem('hindPharmaUser'),role=localStorage.getItem('hindPharmaRole'),loginTime=Number(localStorage.getItem('hindPharmaLoginTime')||0),version=localStorage.getItem('hindPharmaSessionVersion'),expiry=localStorage.getItem('hindPharmaSubscriptionExpiry');if(!token||!username||!VALID_ROLES.includes(role)||version!==SESSION_VERSION||loginTime<=0||Date.now()-loginTime>=SESSION_DURATION_MS||(!['super_admin'].includes(role)&&expiry&&new Date(`${expiry}T23:59:59`)<new Date())){this.clear();return null}return{token,username,role,admin_id:Number(localStorage.getItem('hindPharmaAdminId')||0)||null,business_name:localStorage.getItem('hindPharmaBusinessName')||'',subscription_expiry:expiry||null,loginTime}},
isLoggedIn(){return Boolean(this.get())},hasRole(...roles){const s=this.get();return Boolean(s&&roles.includes(s.role))},isSuperAdmin(){return this.hasRole('super_admin')},isAdmin(){return this.hasRole('admin')},isManager(){return this.hasRole('manager')},isEmployee(){return this.hasRole('employee')},canManageCatalog(){return this.hasRole('admin','manager')},canDelete(){return this.hasRole('admin')},canManageUsers(){return this.hasRole('admin','manager')},canViewDashboard(){return this.hasRole('super_admin','admin','manager')},canWorkOrders(){return this.hasRole('admin','manager','employee')},
clear(){SESSION_KEYS.forEach(key=>localStorage.removeItem(key));sessionStorage.clear()},
requireLogin(){const s=this.get();if(!s){location.replace('login.html');return null}return s},
requireRole(...roles){const s=this.get();if(!s||!roles.includes(s.role)){location.replace(roles.includes('super_admin')?'super-admin-login.html':'login.html');return null}return s},
startExpiryWatcher(onExpire){return setInterval(()=>{if(!this.get()&&typeof onExpire==='function')onExpire()},60000)}
};
