import { TempDataService } from '../temp/temp_file_dataService.js?v=20260830-5';
import { TempSessionService } from '../temp/temp_file_sessionService.js?v=20260830-5';

const session = TempSessionService.requireAdmin();
if (!session) throw new Error('Admin login required.');
const dataService = new TempDataService();
document.getElementById('adminName').textContent = `Signed in as ${session.username}`;
document.getElementById('logoutButton').addEventListener('click', () => { TempSessionService.clear(); location.replace('login.html'); });

function setMessage(id,text,success=false){const element=document.getElementById(id);element.textContent=text;element.className=`message ${success?'success':'error'}`;}
function escapeHtml(value){return String(value??'').replace(/[&<>\"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[character]));}
function formatDate(value){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?String(value):date.toLocaleDateString();}
function confirmDelete(label){return window.confirm(`Delete ${label}?\n\nThis will hide the entry from the website.`);}

async function loadCounts(){try{document.getElementById('medicalCount').textContent=(await dataService.getMedicals()).length;}catch(_){document.getElementById('medicalCount').textContent='—';}try{document.getElementById('productCount').textContent=(await dataService.getProducts()).length;}catch(_){document.getElementById('productCount').textContent='—';}}

async function loadUsers(){const table=document.getElementById('usersTable');try{const users=await dataService.getUsers();document.getElementById('userCount').textContent=users.length;table.innerHTML=users.map(user=>{const identity=encodeURIComponent(user.username);const isCurrent=user.username.toLowerCase()===session.username.toLowerCase();return `<tr><td>${escapeHtml(user.username)}</td><td><span class="pill ${user.role}">${String(user.role||'user').toUpperCase()}</span></td><td class="active">${user.is_active!==false?'ACTIVE':'INACTIVE'}</td><td>${formatDate(user.created_at)}</td><td>${isCurrent?'<span class="protected">CURRENT</span>':`<button class="btn danger deleteUser" data-username="${identity}" type="button">DELETE</button>`}</td></tr>`;}).join('')||'<tr><td colspan="5">No users found.</td></tr>';}catch(error){table.innerHTML=`<tr><td colspan="5">${escapeHtml(error.message)}</td></tr>`;}}

async function loadMedicals(){const table=document.getElementById('medicalsTable');try{const medicals=await dataService.getMedicals();table.innerHTML=medicals.map((medical,index)=>`<tr><td>${escapeHtml(medical.name)}</td><td>${escapeHtml(medical.area||'—')}</td><td><button class="btn danger deleteMedical" data-index="${index}" type="button">DELETE</button></td></tr>`).join('')||'<tr><td colspan="3">No medicals found.</td></tr>';table.querySelectorAll('.deleteMedical').forEach(button=>button.addEventListener('click',async()=>{const items=await dataService.getMedicals();const item=items[Number(button.dataset.index)];if(!item||!confirmDelete(`medical “${item.name}”`))return;await dataService.deleteMedical(item);setMessage('medicalDeleteMessage','Medical deleted successfully.',true);await loadMedicals();loadCounts();}));}catch(error){table.innerHTML=`<tr><td colspan="3">${escapeHtml(error.message)}</td></tr>`;}}

async function loadProducts(){const table=document.getElementById('productsTable');try{const products=await dataService.getProducts();table.innerHTML=products.map((product,index)=>`<tr><td>${escapeHtml(product.name)}</td><td>${escapeHtml(product.code||product.id||'—')}</td><td><button class="btn danger deleteProduct" data-index="${index}" type="button">DELETE</button></td></tr>`).join('')||'<tr><td colspan="3">No products found.</td></tr>';table.querySelectorAll('.deleteProduct').forEach(button=>button.addEventListener('click',async()=>{const items=await dataService.getProducts();const item=items[Number(button.dataset.index)];if(!item||!confirmDelete(`product “${item.name}”`))return;await dataService.deleteProduct(item);setMessage('productDeleteMessage','Product deleted successfully.',true);await loadProducts();loadCounts();}));}catch(error){table.innerHTML=`<tr><td colspan="3">${escapeHtml(error.message)}</td></tr>`;}}

document.getElementById('medicalForm').addEventListener('submit',async event=>{event.preventDefault();const name=document.getElementById('medicalName').value.trim();const area=document.getElementById('medicalArea').value.trim();if(!name)return setMessage('medicalMessage','Medical name is required.');try{const existing=await dataService.getMedicals();if(existing.some(item=>String(item.name).toLowerCase()===name.toLowerCase()))throw new Error('Medical already exists.');await dataService.addMedical({id:`MED-TEMP-${Date.now()}`,name,area,is_active:true});event.target.reset();setMessage('medicalMessage','Medical added successfully.',true);loadMedicals();loadCounts();}catch(error){setMessage('medicalMessage',error.message);}});

document.getElementById('userForm').addEventListener('submit',async event=>{event.preventDefault();const newUsername=document.getElementById('newUsername').value.trim();const password=document.getElementById('newPassword').value;const newRole=document.getElementById('newRole').value;if(!newUsername)return setMessage('userMessage','Username is required.');if(password.length<8)return setMessage('userMessage','Password must be at least 8 characters.');try{const existing=await dataService.getUsers();if(existing.some(item=>item.username.toLowerCase()===newUsername.toLowerCase()))throw new Error('Username already exists.');await dataService.addUser({id:`USR-TEMP-${Date.now()}`,username:newUsername,password_hash:await dataService.sha256(password),role:newRole,is_active:true,created_at:new Date().toISOString()});event.target.reset();setMessage('userMessage','User created successfully.',true);loadUsers();}catch(error){setMessage('userMessage',error.message);}});

document.getElementById('productForm').addEventListener('submit',async event=>{event.preventDefault();const name=document.getElementById('productName').value.trim();if(!name)return setMessage('productMessage','Product name is required.');try{const existing=await dataService.getProducts();const productId=document.getElementById('productId').value.trim()||`ADM-${Date.now()}`;if(existing.some(item=>String(item.id||'').toLowerCase()===productId.toLowerCase()))throw new Error('Product ID already exists.');await dataService.addProduct({id:productId,code:document.getElementById('productCode').value.trim(),name,unit:document.getElementById('productUnit').value.trim(),mrp:Number(document.getElementById('productMrp').value||0),formula:document.getElementById('productFormula').value.trim(),company:document.getElementById('productCompany').value.trim(),is_active:true});event.target.reset();setMessage('productMessage','Product added successfully.',true);loadProducts();loadCounts();}catch(error){setMessage('productMessage',error.message);}});

document.getElementById('usersTable').addEventListener('click',async event=>{const button=event.target.closest('.deleteUser');if(!button)return;const username=decodeURIComponent(button.dataset.username);const user=(await dataService.getUsers()).find(item=>item.username.toLowerCase()===username.toLowerCase());if(!user||!confirmDelete(`user “${user.username}”`))return;await dataService.deleteUser(user);setMessage('userDeleteMessage','User deleted successfully.',true);loadUsers();});
document.getElementById('refreshUsers').addEventListener('click',loadUsers);
document.getElementById('refreshMedicals').addEventListener('click',loadMedicals);
document.getElementById('refreshProducts').addEventListener('click',loadProducts);
TempSessionService.startExpiryWatcher(()=>location.replace('login.html'));
loadUsers();loadMedicals();loadProducts();loadCounts();
